# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BeautyItem' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeautyItem

  target 'BeautyItemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeautyItemUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'SDWebImage'
end
